export const ADD_CHARACTER_TO_FAVORITE = 'ADD_CHARACTER_TO_FAVORITE';
export const REMOVE_CHARACTER_TO_FAVORITE = 'REMOVE_CHARACTER_TO_FAVORITE';
export const ADD_EPISODE_TO_FAVORITE = 'ADD_EPISODE_TO_FAVORITE';
export const REMOVE_EPISODE_TO_FAVORITE = 'REMOVE_EPISODE_TO_FAVORITE';
export const ADD_LOCATION_TO_FAVORITE = 'ADD_LOCATION_TO_FAVORITE';
export const REMOVE_LOCATION_TO_FAVORITE = 'REMOVE_LOCATION_TO_FAVORITE';
export const ADD_CHARACTER_TO_STORE = 'ADD_CHARACTER_TO_STORE';
export const REMOVE_CHARACTER_TO_STORE = 'REMOVE_CHARACTER_TO_STORE';